all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/chase_lab.pem
    ansible_python_interpreter: /usr/bin/python
  hosts:
    ansible01:
  children:
    webservers:
      hosts:
        ansible01:
        ansible02:
        ansible03:
